### PR TITLE
Update langchain_quick_start.ipynb

### PR DESCRIPTION
**Pull request by ABirHAsan123-beep**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/langchain-google-alloydb-pg-python/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by ABirHAsan123-beep** [comment]
#154

**Review by ABirHAsan123-beep — COMMENTED** [review]
image (9)

**Comment by ABirHAsan123-beep** [comment]
https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/154/commits/490786acf3356d480e02829c83f6c4bd34faac3b

**Comment by jackwotherspoon** [comment]
This seems a little suspicious @averikitsch we may want to monitor this, I can't tell if this user is trying to be malicious or not

**Pull request closed without merging**
